#include <stdio.h>
#include <cs50.h>

int main(void)
{
    //Prompt user for pyramid height within specified parameters
    int userInput;
    do
    {
        userInput = get_int("Height: ");
    }
    while (userInput < 1 || userInput > 8);

    /*
        Right-aligned pyramid generated by deincrementing spaces with a nested for loop (k),
        while other for loop (j) prints blocks out and main for loop (i) takes care of line breaks.
    */

    for (int i = 0; i < userInput; i++)
    {

        for (int k = userInput - 1; k > i;  k--)
        {
            printf(" ");
        }

        for (int j = 0; j <= i; j++)
        {
            printf("#");
        }
        printf("\n");
    }
}